name: A Sussex Garden
favicon: null
layout_spectrum: 1
typography_spectrum: 0.17419
title: An online diary and information on our Sussex Garden
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77131740-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.1875
  lightness: 0.9060799505095929
  saturation: 0.6875
  rhythmicContrast: 0.8338699727319181
purpose: []
